from typing import Annotated
import os
import pandas as pd
from datetime import datetime

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.templating import Jinja2Templates
from fastapi.param_functions import Depends
from sqlmodel import Session

from ..models.db_models import User
from ..services import auth_service
from ..dao import db
from ..config import settings

router = APIRouter(tags=['vega-live-chart'])
templates = Jinja2Templates(directory="app/templates") # Adjust path if necessary

@router.get("/vega-live-chart", response_class=HTMLResponse)
async def vega_live_chart_page(
    request: Request,
    current_user: Annotated[User, Depends(auth_service.get_current_user)],
    db_session: Session = Depends(db.get_session)
):
    context = {
        "request": request,
        "base_url": request.state.base_url,
        "title": "Live Vega Analysis",
        "current_menu": "Vega_Live_Chart",
        "user_type": current_user.user_type
    }
    return templates.TemplateResponse("vega_live_chart.html", context)


@router.get("/api/vega-live-data")
async def get_vega_live_data(
    current_user: Annotated[User, Depends(auth_service.get_current_user)],
    db_session: Session = Depends(db.get_session)
):
    try:
        # FIX: Look for the file actually generated by the strategy engine
        filename = "Vega_Live.csv"
        csv_path = os.path.join(settings.csv_folder_path, filename) 
        
        if not os.path.exists(csv_path):
            return JSONResponse(
                status_code=404,
                content={"error": f"Data file {filename} not found yet."}
            )
        
        # Read CSV file
        df = pd.read_csv(csv_path)
        
        if 'Timestamp' not in df.columns or 'CE_Vega' not in df.columns or 'PE_Vega' not in df.columns:
            return JSONResponse(
                status_code=400,
                content={"error": "CSV file missing required columns."}
            )
            
        # FIX: Filter for only today's data so the chart resets every morning
        today = datetime.now().strftime('%Y-%m-%d')
        df = df[df['Timestamp'].str.startswith(today)]
        
        # Drop NaNs
        df = df.dropna(subset=['CE_Vega', 'PE_Vega'])
        
        # Return cleanly separated arrays
        return JSONResponse(content={
            "labels": df['Timestamp'].tolist(),
            "ce_vega": df['CE_Vega'].tolist(),
            "pe_vega": df['PE_Vega'].tolist(),
            "ce_vomma": df['CE_Vomma'].tolist() if 'CE_Vomma' in df.columns else [],
            "pe_vomma": df['PE_Vomma'].tolist() if 'PE_Vomma' in df.columns else []
        })
        
    except Exception as e:
        return JSONResponse(
            status_code=500,
            content={"error": f"Error reading live Vega data: {str(e)}"}
        )